SET search_path TO public;
INSERT INTO device_profiles (id, device_id, safety_acknowledged, safety_acknowledged_at, yearly_subscription_active, subscription_status)
VALUES (1, 'demo-device', true, NOW(), false, 'inactive');

INSERT INTO lab_reports (
  id, device_profile_id, report_label, lab_name, source_type, content_type, original_filename,
  image_public_url, image_object_key, collected_on, is_historical_upload, analysis_status,
  preview_summary, urgent_level, urgent_label, urgent_message, flagged_items, preview_takeaways,
  timeline_hint, timeline_completeness_score, free_ai_question_used, unlocked, unlock_source,
  unlocked_at, purchase_price_label
) VALUES
(
  1, 1, 'Annual Wellness 2022', 'LabBuddy Scan', 'library', 'image/jpeg', 'labs-2022.jpg',
  'https://example.com/labs-2022.jpg', 'demo/uploads/labs-2022.jpg', '2022-05-04', true, 'ready',
  'A few items stand out, especially LDL Cholesterol. This first look is meant to calm uncertainty, not replace a clinician visit. Unlocking the full report will show what each marker may mean and which follow-up questions to ask.',
  'medium', 'Worth following up soon', 'A few markers look outside the usual range. This is usually best handled with a clinician follow-up rather than panic.',
  '[{"biomarker_key":"ldl","label":"LDL Cholesterol","status":"high","reason":"Your LDL is above the usual target range and may be worth reviewing soon."},{"biomarker_key":"a1c","label":"Hemoglobin A1C","status":"high","reason":"Your A1C is above the usual range and deserves follow-up."}]'::json,
  '["Educational only—not medical advice or diagnosis.","One free follow-up question is included before unlock.","Unlock this report to see every biomarker card and clinician questions."]'::json,
  'This older report can help build your timeline once it is unlocked.', 0.40, true, true, 'report_unlock', NOW(), '$4.99'
),
(
  2, 1, 'Checkup 2023', 'LabBuddy Scan', 'library', 'image/jpeg', 'labs-2023.jpg',
  'https://example.com/labs-2023.jpg', 'demo/uploads/labs-2023.jpg', '2023-08-11', true, 'ready',
  'A few items stand out, especially LDL Cholesterol. This first look is meant to calm uncertainty, not replace a clinician visit. Unlocking the full report will show what each marker may mean and which follow-up questions to ask.',
  'low', 'Nothing looks immediately urgent', 'This preview does not suggest a same-day emergency from the visible markers alone. If you feel very unwell or have severe symptoms, seek urgent care.',
  '[{"biomarker_key":"ldl","label":"LDL Cholesterol","status":"high","reason":"Your LDL is above the usual target range and may be worth reviewing soon."}]'::json,
  '["Educational only—not medical advice or diagnosis.","One free follow-up question is included before unlock.","Unlock this report to see every biomarker card and clinician questions."]'::json,
  'Your trend view is taking shape—older reports will make the story clearer.', 0.60, false, true, 'report_unlock', NOW(), '$4.99'
),
(
  3, 1, 'Latest report', 'LabBuddy Scan', 'camera', 'image/jpeg', 'labs-latest.jpg',
  'https://example.com/labs-latest.jpg', 'demo/uploads/labs-latest.jpg', '2024-11-18', false, 'ready',
  'A few items stand out, especially Hemoglobin A1C. This first look is meant to calm uncertainty, not replace a clinician visit. Unlocking the full report will show what each marker may mean and which follow-up questions to ask.',
  'medium', 'Worth following up soon', 'A few markers look outside the usual range. This is usually best handled with a clinician follow-up rather than panic.',
  '[{"biomarker_key":"a1c","label":"Hemoglobin A1C","status":"high","reason":"Your A1C is above the usual range and deserves follow-up."},{"biomarker_key":"triglycerides","label":"Triglycerides","status":"high","reason":"Your triglycerides are above range and could improve with follow-up."}]'::json,
  '["Educational only—not medical advice or diagnosis.","One free follow-up question is included before unlock.","Unlock this report to see every biomarker card and clinician questions."]'::json,
  'One more unlocked report will make your trendlines much more useful.', 0.60, false, false, NULL, NULL, '$4.99'
);

INSERT INTO biomarker_results (
  report_id, biomarker_key, display_name, display_order, category, value_text, numeric_value, unit,
  reference_text, reference_low, reference_high, status, status_label, quick_takeaway,
  simple_translation, calm_explanation, confidence_label, confidence_score, clinician_questions,
  trend_note
) VALUES
(1, 'ldl', 'LDL Cholesterol', 1, 'Heart health', '142', 142, 'mg/dL', '0–99 mg/dL', 0, 99, 'high', 'Above range', 'Your LDL is above the usual target range and may be worth reviewing soon.', 'LDL is often called the less helpful cholesterol because higher levels can raise heart risk over time.', 'Mild LDL elevations are common and can shift with diet, exercise, weight changes, genetics, and medicines. It is usually something to review thoughtfully, not panic about.', 'Moderate', 0.74, '["Should I repeat my cholesterol panel fasting?","What LDL goal makes sense for my overall risk?"]'::json, 'This result becomes more useful when compared against your later reports.'),
(1, 'hdl', 'HDL Cholesterol', 2, 'Heart health', '43', 43, 'mg/dL', '40–90 mg/dL', 40, 90, 'normal', 'In range', 'Your HDL is in a reassuring range.', 'HDL is often called the helpful cholesterol because higher levels can support heart health.', 'HDL may be influenced by exercise, weight, genetics, smoking, and triglyceride levels. A lower number is worth improving over time, not fearing in the moment.', 'Higher', 0.86, '["What habits would help improve my HDL?","How should I look at HDL together with LDL and triglycerides?"]'::json, 'HDL has been stable across your older reports.'),
(1, 'triglycerides', 'Triglycerides', 3, 'Heart health', '168', 168, 'mg/dL', '0–149 mg/dL', 0, 149, 'high', 'Above range', 'Your triglycerides are above range and could improve with follow-up.', 'Triglycerides are a kind of blood fat that can rise with sugar intake, alcohol, weight changes, or not fasting.', 'A mild rise can happen for simple reasons like a recent meal, alcohol, or insulin resistance. Trends over time matter more than a single number.', 'Moderate', 0.74, '["Do I need to repeat this test fasting?","Could food, alcohol, or medication explain this result?"]'::json, 'Your triglycerides have improved since 2022.'),
(1, 'a1c', 'Hemoglobin A1C', 4, 'Blood sugar', '5.9', 5.9, '%', '4.0–5.6 %', 4.0, 5.6, 'high', 'Above range', 'Your A1C is above the usual range and deserves follow-up.', 'A1C estimates your average blood sugar over about 3 months.', 'A borderline or mildly elevated A1C can happen before diabetes and may improve with habits or treatment. It is important, but usually not a same-day emergency by itself.', 'Moderate', 0.74, '["Should I repeat my A1C or check fasting glucose too?","What changes would make the biggest difference before my next test?"]'::json, 'This is the first point in your A1C timeline.'),
(1, 'glucose', 'Glucose', 5, 'Blood sugar', '104', 104, 'mg/dL', '70–99 mg/dL', 70, 99, 'high', 'Above range', 'Your glucose is a bit higher than expected and should be reviewed in context.', 'Glucose is the amount of sugar in your blood right now.', 'Food, stress, illness, sleep, and fasting status can all affect glucose. One mildly high value is usually not enough to diagnose anything by itself.', 'Moderate', 0.74, '["Was this test fasting, and does that change how we interpret it?","Do I need repeat testing or more blood sugar screening?"]'::json, 'Compare this with later fasting results before drawing conclusions.'),
(1, 'creatinine', 'Creatinine', 6, 'Kidney function', '1.02', 1.02, 'mg/dL', '0.6–1.3 mg/dL', 0.6, 1.3, 'normal', 'In range', 'Your creatinine is in a reassuring range.', 'Creatinine helps estimate how well your kidneys are filtering.', 'Creatinine can shift with hydration, muscle mass, exercise, medicines, and kidney function. Mild changes are not always dangerous, but they do deserve context.', 'Higher', 0.86, '["Could hydration or medication affect this creatinine result?","Do I need kidney follow-up or repeat labs soon?"]'::json, 'Kidney markers remain steady across your saved reports.'),
(2, 'ldl', 'LDL Cholesterol', 1, 'Heart health', '128', 128, 'mg/dL', '0–99 mg/dL', 0, 99, 'high', 'Above range', 'Your LDL is above the usual target range and may be worth reviewing soon.', 'LDL is often called the less helpful cholesterol because higher levels can raise heart risk over time.', 'Mild LDL elevations are common and can shift with diet, exercise, weight changes, genetics, and medicines. It is usually something to review thoughtfully, not panic about.', 'Moderate', 0.74, '["Should I repeat my cholesterol panel fasting?","What LDL goal makes sense for my overall risk?"]'::json, 'LDL is improving compared with 2022.'),
(2, 'hdl', 'HDL Cholesterol', 2, 'Heart health', '48', 48, 'mg/dL', '40–90 mg/dL', 40, 90, 'normal', 'In range', 'Your HDL is in a reassuring range.', 'HDL is often called the helpful cholesterol because higher levels can support heart health.', 'HDL may be influenced by exercise, weight, genetics, smoking, and triglyceride levels. A lower number is worth improving over time, not fearing in the moment.', 'Higher', 0.86, '["What habits would help improve my HDL?","How should I look at HDL together with LDL and triglycerides?"]'::json, 'HDL has moved in a reassuring direction.'),
(2, 'triglycerides', 'Triglycerides', 3, 'Heart health', '144', 144, 'mg/dL', '0–149 mg/dL', 0, 149, 'normal', 'In range', 'Your triglycerides are in a comfortable range.', 'Triglycerides are a kind of blood fat that can rise with sugar intake, alcohol, weight changes, or not fasting.', 'A mild rise can happen for simple reasons like a recent meal, alcohol, or insulin resistance. Trends over time matter more than a single number.', 'Higher', 0.86, '["Do I need to repeat this test fasting?","Could food, alcohol, or medication explain this result?"]'::json, 'This improved versus your older report.'),
(2, 'a1c', 'Hemoglobin A1C', 4, 'Blood sugar', '5.7', 5.7, '%', '4.0–5.6 %', 4.0, 5.6, 'high', 'Above range', 'Your A1C is above the usual range and deserves follow-up.', 'A1C estimates your average blood sugar over about 3 months.', 'A borderline or mildly elevated A1C can happen before diabetes and may improve with habits or treatment. It is important, but usually not a same-day emergency by itself.', 'Moderate', 0.74, '["Should I repeat my A1C or check fasting glucose too?","What changes would make the biggest difference before my next test?"]'::json, 'Your A1C trend is slightly improving.'),
(2, 'glucose', 'Glucose', 5, 'Blood sugar', '99', 99, 'mg/dL', '70–99 mg/dL', 70, 99, 'normal', 'In range', 'Your glucose is within the common fasting range.', 'Glucose is the amount of sugar in your blood right now.', 'Food, stress, illness, sleep, and fasting status can all affect glucose. One mildly high value is usually not enough to diagnose anything by itself.', 'Higher', 0.86, '["Was this test fasting, and does that change how we interpret it?","Do I need repeat testing or more blood sugar screening?"]'::json, 'Glucose is more reassuring here than in 2022.'),
(2, 'creatinine', 'Creatinine', 6, 'Kidney function', '0.95', 0.95, 'mg/dL', '0.6–1.3 mg/dL', 0.6, 1.3, 'normal', 'In range', 'Your creatinine is in a reassuring range.', 'Creatinine helps estimate how well your kidneys are filtering.', 'Creatinine can shift with hydration, muscle mass, exercise, medicines, and kidney function. Mild changes are not always dangerous, but they do deserve context.', 'Higher', 0.86, '["Could hydration or medication affect this creatinine result?","Do I need kidney follow-up or repeat labs soon?"]'::json, 'Kidney markers remain steady across your saved reports.'),
(3, 'ldl', 'LDL Cholesterol', 1, 'Heart health', '119', 119, 'mg/dL', '0–99 mg/dL', 0, 99, 'high', 'Above range', 'Your LDL is above the usual target range and may be worth reviewing soon.', 'LDL is often called the less helpful cholesterol because higher levels can raise heart risk over time.', 'Mild LDL elevations are common and can shift with diet, exercise, weight changes, genetics, and medicines. It is usually something to review thoughtfully, not panic about.', 'Moderate', 0.74, '["Should I repeat my cholesterol panel fasting?","What LDL goal makes sense for my overall risk?"]'::json, 'Unlock this report to compare it against your older LDL results.'),
(3, 'hdl', 'HDL Cholesterol', 2, 'Heart health', '51', 51, 'mg/dL', '40–90 mg/dL', 40, 90, 'normal', 'In range', 'Your HDL is in a reassuring range.', 'HDL is often called the helpful cholesterol because higher levels can support heart health.', 'HDL may be influenced by exercise, weight, genetics, smoking, and triglyceride levels. A lower number is worth improving over time, not fearing in the moment.', 'Higher', 0.86, '["What habits would help improve my HDL?","How should I look at HDL together with LDL and triglycerides?"]'::json, 'Unlock this report to place HDL on your longer timeline.'),
(3, 'triglycerides', 'Triglycerides', 3, 'Heart health', '172', 172, 'mg/dL', '0–149 mg/dL', 0, 149, 'high', 'Above range', 'Your triglycerides are above range and could improve with follow-up.', 'Triglycerides are a kind of blood fat that can rise with sugar intake, alcohol, weight changes, or not fasting.', 'A mild rise can happen for simple reasons like a recent meal, alcohol, or insulin resistance. Trends over time matter more than a single number.', 'Moderate', 0.74, '["Do I need to repeat this test fasting?","Could food, alcohol, or medication explain this result?"]'::json, 'Unlock this report to see whether this is a one-time bump or part of a trend.'),
(3, 'a1c', 'Hemoglobin A1C', 4, 'Blood sugar', '6.1', 6.1, '%', '4.0–5.6 %', 4.0, 5.6, 'high', 'Above range', 'Your A1C is above the usual range and deserves follow-up.', 'A1C estimates your average blood sugar over about 3 months.', 'A borderline or mildly elevated A1C can happen before diabetes and may improve with habits or treatment. It is important, but usually not a same-day emergency by itself.', 'Moderate', 0.74, '["Should I repeat my A1C or check fasting glucose too?","What changes would make the biggest difference before my next test?"]'::json, 'Unlock this report to see how your A1C compares with earlier years.'),
(3, 'glucose', 'Glucose', 5, 'Blood sugar', '108', 108, 'mg/dL', '70–99 mg/dL', 70, 99, 'high', 'Above range', 'Your glucose is a bit higher than expected and should be reviewed in context.', 'Glucose is the amount of sugar in your blood right now.', 'Food, stress, illness, sleep, and fasting status can all affect glucose. One mildly high value is usually not enough to diagnose anything by itself.', 'Moderate', 0.74, '["Was this test fasting, and does that change how we interpret it?","Do I need repeat testing or more blood sugar screening?"]'::json, 'Unlock this report to compare today with prior glucose results.'),
(3, 'creatinine', 'Creatinine', 6, 'Kidney function', '1.01', 1.01, 'mg/dL', '0.6–1.3 mg/dL', 0.6, 1.3, 'normal', 'In range', 'Your creatinine is in a reassuring range.', 'Creatinine helps estimate how well your kidneys are filtering.', 'Creatinine can shift with hydration, muscle mass, exercise, medicines, and kidney function. Mild changes are not always dangerous, but they do deserve context.', 'Higher', 0.86, '["Could hydration or medication affect this creatinine result?","Do I need kidney follow-up or repeat labs soon?"]'::json, 'Kidney markers remain steady across your saved reports.');

INSERT INTO report_questions (report_id, question_text, answer_text, access_tier)
VALUES
(1, 'Should I be worried about my A1C?', 'Your A1C is slightly above the usual range, which is worth following up but usually not a same-day emergency by itself. A good next step is to ask whether repeat testing or fasting glucose would help clarify the picture.', 'free-preview');