"""push

Revision ID: 7030df778868
Revises: 
Create Date: 2026-03-08 22:27:45.920865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7030df778868'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('safety_acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('safety_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yearly_subscription_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('subscription_status', sa.String(length=32), server_default=sa.text("'inactive'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_profiles_device_id'), 'device_profiles', ['device_id'], unique=True)
    op.create_table('lab_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_profile_id', sa.Integer(), nullable=False),
    sa.Column('report_label', sa.String(length=120), nullable=False),
    sa.Column('lab_name', sa.String(length=120), server_default=sa.text("'LabBuddy Scan'"), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('image_public_url', sa.String(length=1000), nullable=False),
    sa.Column('image_object_key', sa.String(length=500), nullable=False),
    sa.Column('collected_on', sa.Date(), nullable=True),
    sa.Column('is_historical_upload', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), server_default=sa.text("'ready'"), nullable=False),
    sa.Column('preview_summary', sa.Text(), nullable=False),
    sa.Column('urgent_level', sa.String(length=24), nullable=False),
    sa.Column('urgent_label', sa.String(length=120), nullable=False),
    sa.Column('urgent_message', sa.Text(), nullable=False),
    sa.Column('flagged_items', sa.JSON(), nullable=False),
    sa.Column('preview_takeaways', sa.JSON(), nullable=False),
    sa.Column('timeline_hint', sa.Text(), nullable=False),
    sa.Column('timeline_completeness_score', sa.Float(), nullable=False),
    sa.Column('free_ai_question_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('unlocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('unlock_source', sa.String(length=32), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_price_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_profile_id'], ['device_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_reports_device_profile_id'), 'lab_reports', ['device_profile_id'], unique=False)
    op.create_table('biomarker_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('biomarker_key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('value_text', sa.String(length=64), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('reference_text', sa.String(length=120), nullable=False),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_label', sa.String(length=80), nullable=False),
    sa.Column('quick_takeaway', sa.Text(), nullable=False),
    sa.Column('simple_translation', sa.Text(), nullable=False),
    sa.Column('calm_explanation', sa.Text(), nullable=False),
    sa.Column('confidence_label', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('clinician_questions', sa.JSON(), nullable=False),
    sa.Column('trend_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lab_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biomarker_results_biomarker_key'), 'biomarker_results', ['biomarker_key'], unique=False)
    op.create_index(op.f('ix_biomarker_results_report_id'), 'biomarker_results', ['report_id'], unique=False)
    op.create_table('report_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('access_tier', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lab_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_questions_report_id'), 'report_questions', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_questions_report_id'), table_name='report_questions')
    op.drop_table('report_questions')
    op.drop_index(op.f('ix_biomarker_results_report_id'), table_name='biomarker_results')
    op.drop_index(op.f('ix_biomarker_results_biomarker_key'), table_name='biomarker_results')
    op.drop_table('biomarker_results')
    op.drop_index(op.f('ix_lab_reports_device_profile_id'), table_name='lab_reports')
    op.drop_table('lab_reports')
    op.drop_index(op.f('ix_device_profiles_device_id'), table_name='device_profiles')
    op.drop_table('device_profiles')
    # ### end Alembic commands ###
